### ISSUE TITLE
[Feature request] Compile for mac

### ISSUE THREAD

**Issue by alkurop** [rncbc/jack_link#3]
Hey.
This looks like an awesome lib.
I'm a mac user not for such a long time though. I used to be with linux, so I know the audio stack on linux - Jack server etc.
I'm basically trying to sync Hydrogen drum machine and Ableton on mac via the Jack Server.
This lib seems like an answer adding sync for Ableton with jack.
Is it possible to compile it for mac though?
This would be robust if we could pull this off

**Comment by rncbc** [comment]
have no clue how to adapt for macosx but i think it could be just a matter of tweaking the Makefile little  bit if any at all.

note that jack_link is currently a console/terminal/CLI/comand line program utility but I guess it showuld work OOTB on any system, provided a JACK server is up and running.

cheers

ps. no fan here of the bitten-fruit corp. sorry :)

**Comment by alkurop** [comment]
I also wonder, are you able to run ableton on linux?
Is it ported, or you are using wine?

**Comment by alkurop** [comment]
brilliant, it works
ur best
